/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthTradespacesRouteRouteImport } from './routes/_auth/tradespaces/route'
import { Route as AuthTradespacesTradespaceIdRouteRouteImport } from './routes/_auth/tradespaces/$tradespaceId/route'
import { Route as AuthTradespacesTradespaceIdTopicsRouteImport } from './routes/_auth/tradespaces/$tradespaceId/topics'
import { Route as AuthTradespacesTradespaceIdProductsRouteImport } from './routes/_auth/tradespaces/$tradespaceId/products'
import { Route as AuthTradespacesTradespaceIdForumsRouteImport } from './routes/_auth/tradespaces/$tradespaceId/forums'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthTradespacesRouteRoute = AuthTradespacesRouteRouteImport.update({
  id: '/tradespaces',
  path: '/tradespaces',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthTradespacesTradespaceIdRouteRoute =
  AuthTradespacesTradespaceIdRouteRouteImport.update({
    id: '/$tradespaceId',
    path: '/$tradespaceId',
    getParentRoute: () => AuthTradespacesRouteRoute,
  } as any)

const AuthTradespacesTradespaceIdTopicsRoute =
  AuthTradespacesTradespaceIdTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthTradespacesTradespaceIdRouteRoute,
  } as any)

const AuthTradespacesTradespaceIdProductsRoute =
  AuthTradespacesTradespaceIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthTradespacesTradespaceIdRouteRoute,
  } as any)

const AuthTradespacesTradespaceIdForumsRoute =
  AuthTradespacesTradespaceIdForumsRouteImport.update({
    id: '/forums',
    path: '/forums',
    getParentRoute: () => AuthTradespacesTradespaceIdRouteRoute,
  } as any)

// Children Interfaces
interface AuthTradespacesTradespaceIdRouteRouteChildren {
  AuthTradespacesTradespaceIdForumsRoute: typeof AuthTradespacesTradespaceIdForumsRoute
  AuthTradespacesTradespaceIdProductsRoute: typeof AuthTradespacesTradespaceIdProductsRoute
  AuthTradespacesTradespaceIdTopicsRoute: typeof AuthTradespacesTradespaceIdTopicsRoute
}

const AuthTradespacesTradespaceIdRouteRouteChildren: AuthTradespacesTradespaceIdRouteRouteChildren = {
  AuthTradespacesTradespaceIdForumsRoute,
  AuthTradespacesTradespaceIdProductsRoute,
  AuthTradespacesTradespaceIdTopicsRoute,
}

const AuthTradespacesTradespaceIdRouteRouteWithChildren =
  AuthTradespacesTradespaceIdRouteRoute._addFileChildren(AuthTradespacesTradespaceIdRouteRouteChildren)

interface AuthTradespacesRouteRouteChildren {
  AuthTradespacesTradespaceIdRouteRoute: typeof AuthTradespacesTradespaceIdRouteRouteWithChildren
}

const AuthTradespacesRouteRouteChildren: AuthTradespacesRouteRouteChildren = {
  AuthTradespacesTradespaceIdRouteRoute: AuthTradespacesTradespaceIdRouteRouteWithChildren,
}

const AuthTradespacesRouteRouteWithChildren =
  AuthTradespacesRouteRoute._addFileChildren(AuthTradespacesRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthTradespacesRouteRoute: typeof AuthTradespacesRouteRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSearchRoute: typeof AuthSearchRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthTradespacesRouteRoute: AuthTradespacesRouteRouteWithChildren,
  AuthDashboardRoute,
  AuthSearchRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren)

interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute,
  SignupRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()
