/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCartRouteImport } from './routes/_auth/cart'
import { Route as AuthTradespacesRouteRouteImport } from './routes/_auth/tradespaces/route'
import { Route as AuthTradespacesTradespaceIdRouteRouteImport } from './routes/_auth/tradespaces/$tradespaceId/route'
import { Route as AuthTradespacesTradespaceIdTopicsRouteImport } from './routes/_auth/tradespaces/$tradespaceId/topics'
import { Route as AuthTradespacesTradespaceIdProductsRouteImport } from './routes/_auth/tradespaces/$tradespaceId/products'
import { Route as AuthTradespacesTradespaceIdForumsRouteImport } from './routes/_auth/tradespaces/$tradespaceId/forums'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCartRoute = AuthCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTradespacesRouteRoute = AuthTradespacesRouteRouteImport.update({
  id: '/tradespaces',
  path: '/tradespaces',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTradespacesTradespaceIdRouteRoute =
  AuthTradespacesTradespaceIdRouteRouteImport.update({
    id: '/$tradespaceId',
    path: '/$tradespaceId',
    getParentRoute: () => AuthTradespacesRouteRoute,
  } as any)
const AuthTradespacesTradespaceIdTopicsRoute =
  AuthTradespacesTradespaceIdTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthTradespacesTradespaceIdRouteRoute,
  } as any)
const AuthTradespacesTradespaceIdProductsRoute =
  AuthTradespacesTradespaceIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthTradespacesTradespaceIdRouteRoute,
  } as any)
const AuthTradespacesTradespaceIdForumsRoute =
  AuthTradespacesTradespaceIdForumsRouteImport.update({
    id: '/forums',
    path: '/forums',
    getParentRoute: () => AuthTradespacesTradespaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tradespaces': typeof AuthTradespacesRouteRouteWithChildren
  '/cart': typeof AuthCartRoute
  '/dashboard': typeof AuthDashboardRoute
  '/search': typeof AuthSearchRoute
  '/settings': typeof AuthSettingsRoute
  '/tradespaces/$tradespaceId': typeof AuthTradespacesTradespaceIdRouteRouteWithChildren
  '/tradespaces/$tradespaceId/forums': typeof AuthTradespacesTradespaceIdForumsRoute
  '/tradespaces/$tradespaceId/products': typeof AuthTradespacesTradespaceIdProductsRoute
  '/tradespaces/$tradespaceId/topics': typeof AuthTradespacesTradespaceIdTopicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tradespaces': typeof AuthTradespacesRouteRouteWithChildren
  '/cart': typeof AuthCartRoute
  '/dashboard': typeof AuthDashboardRoute
  '/search': typeof AuthSearchRoute
  '/settings': typeof AuthSettingsRoute
  '/tradespaces/$tradespaceId': typeof AuthTradespacesTradespaceIdRouteRouteWithChildren
  '/tradespaces/$tradespaceId/forums': typeof AuthTradespacesTradespaceIdForumsRoute
  '/tradespaces/$tradespaceId/products': typeof AuthTradespacesTradespaceIdProductsRoute
  '/tradespaces/$tradespaceId/topics': typeof AuthTradespacesTradespaceIdTopicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/tradespaces': typeof AuthTradespacesRouteRouteWithChildren
  '/_auth/cart': typeof AuthCartRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/tradespaces/$tradespaceId': typeof AuthTradespacesTradespaceIdRouteRouteWithChildren
  '/_auth/tradespaces/$tradespaceId/forums': typeof AuthTradespacesTradespaceIdForumsRoute
  '/_auth/tradespaces/$tradespaceId/products': typeof AuthTradespacesTradespaceIdProductsRoute
  '/_auth/tradespaces/$tradespaceId/topics': typeof AuthTradespacesTradespaceIdTopicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/tradespaces'
    | '/cart'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/tradespaces/$tradespaceId'
    | '/tradespaces/$tradespaceId/forums'
    | '/tradespaces/$tradespaceId/products'
    | '/tradespaces/$tradespaceId/topics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/tradespaces'
    | '/cart'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/tradespaces/$tradespaceId'
    | '/tradespaces/$tradespaceId/forums'
    | '/tradespaces/$tradespaceId/products'
    | '/tradespaces/$tradespaceId/topics'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/tradespaces'
    | '/_auth/cart'
    | '/_auth/dashboard'
    | '/_auth/search'
    | '/_auth/settings'
    | '/_auth/tradespaces/$tradespaceId'
    | '/_auth/tradespaces/$tradespaceId/forums'
    | '/_auth/tradespaces/$tradespaceId/products'
    | '/_auth/tradespaces/$tradespaceId/topics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/cart': {
      id: '/_auth/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthCartRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tradespaces': {
      id: '/_auth/tradespaces'
      path: '/tradespaces'
      fullPath: '/tradespaces'
      preLoaderRoute: typeof AuthTradespacesRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tradespaces/$tradespaceId': {
      id: '/_auth/tradespaces/$tradespaceId'
      path: '/$tradespaceId'
      fullPath: '/tradespaces/$tradespaceId'
      preLoaderRoute: typeof AuthTradespacesTradespaceIdRouteRouteImport
      parentRoute: typeof AuthTradespacesRouteRoute
    }
    '/_auth/tradespaces/$tradespaceId/topics': {
      id: '/_auth/tradespaces/$tradespaceId/topics'
      path: '/topics'
      fullPath: '/tradespaces/$tradespaceId/topics'
      preLoaderRoute: typeof AuthTradespacesTradespaceIdTopicsRouteImport
      parentRoute: typeof AuthTradespacesTradespaceIdRouteRoute
    }
    '/_auth/tradespaces/$tradespaceId/products': {
      id: '/_auth/tradespaces/$tradespaceId/products'
      path: '/products'
      fullPath: '/tradespaces/$tradespaceId/products'
      preLoaderRoute: typeof AuthTradespacesTradespaceIdProductsRouteImport
      parentRoute: typeof AuthTradespacesTradespaceIdRouteRoute
    }
    '/_auth/tradespaces/$tradespaceId/forums': {
      id: '/_auth/tradespaces/$tradespaceId/forums'
      path: '/forums'
      fullPath: '/tradespaces/$tradespaceId/forums'
      preLoaderRoute: typeof AuthTradespacesTradespaceIdForumsRouteImport
      parentRoute: typeof AuthTradespacesTradespaceIdRouteRoute
    }
  }
}

interface AuthTradespacesTradespaceIdRouteRouteChildren {
  AuthTradespacesTradespaceIdForumsRoute: typeof AuthTradespacesTradespaceIdForumsRoute
  AuthTradespacesTradespaceIdProductsRoute: typeof AuthTradespacesTradespaceIdProductsRoute
  AuthTradespacesTradespaceIdTopicsRoute: typeof AuthTradespacesTradespaceIdTopicsRoute
}

const AuthTradespacesTradespaceIdRouteRouteChildren: AuthTradespacesTradespaceIdRouteRouteChildren =
  {
    AuthTradespacesTradespaceIdForumsRoute:
      AuthTradespacesTradespaceIdForumsRoute,
    AuthTradespacesTradespaceIdProductsRoute:
      AuthTradespacesTradespaceIdProductsRoute,
    AuthTradespacesTradespaceIdTopicsRoute:
      AuthTradespacesTradespaceIdTopicsRoute,
  }

const AuthTradespacesTradespaceIdRouteRouteWithChildren =
  AuthTradespacesTradespaceIdRouteRoute._addFileChildren(
    AuthTradespacesTradespaceIdRouteRouteChildren,
  )

interface AuthTradespacesRouteRouteChildren {
  AuthTradespacesTradespaceIdRouteRoute: typeof AuthTradespacesTradespaceIdRouteRouteWithChildren
}

const AuthTradespacesRouteRouteChildren: AuthTradespacesRouteRouteChildren = {
  AuthTradespacesTradespaceIdRouteRoute:
    AuthTradespacesTradespaceIdRouteRouteWithChildren,
}

const AuthTradespacesRouteRouteWithChildren =
  AuthTradespacesRouteRoute._addFileChildren(AuthTradespacesRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthTradespacesRouteRoute: typeof AuthTradespacesRouteRouteWithChildren
  AuthCartRoute: typeof AuthCartRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSearchRoute: typeof AuthSearchRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthTradespacesRouteRoute: AuthTradespacesRouteRouteWithChildren,
  AuthCartRoute: AuthCartRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSearchRoute: AuthSearchRoute,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
